/**
 * @fileoverview gRPC-Web generated client stub for randomPackage
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.20.3
// source: proto/random.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb';
import * as proto_random_pb from '../proto/random_pb';


export class RandomClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorChatInitiate = new grpcWeb.MethodDescriptor(
    '/randomPackage.Random/ChatInitiate',
    grpcWeb.MethodType.UNARY,
    proto_random_pb.InitiateRequest,
    proto_random_pb.InitiateResponse,
    (request: proto_random_pb.InitiateRequest) => {
      return request.serializeBinary();
    },
    proto_random_pb.InitiateResponse.deserializeBinary
  );

  chatInitiate(
    request: proto_random_pb.InitiateRequest,
    metadata: grpcWeb.Metadata | null): Promise<proto_random_pb.InitiateResponse>;

  chatInitiate(
    request: proto_random_pb.InitiateRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_random_pb.InitiateResponse) => void): grpcWeb.ClientReadableStream<proto_random_pb.InitiateResponse>;

  chatInitiate(
    request: proto_random_pb.InitiateRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_random_pb.InitiateResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/randomPackage.Random/ChatInitiate',
        request,
        metadata || {},
        this.methodDescriptorChatInitiate,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/randomPackage.Random/ChatInitiate',
    request,
    metadata || {},
    this.methodDescriptorChatInitiate);
  }

  methodDescriptorSendMessage = new grpcWeb.MethodDescriptor(
    '/randomPackage.Random/SendMessage',
    grpcWeb.MethodType.UNARY,
    proto_random_pb.MessageRequest,
    google_protobuf_empty_pb.Empty,
    (request: proto_random_pb.MessageRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  sendMessage(
    request: proto_random_pb.MessageRequest,
    metadata: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  sendMessage(
    request: proto_random_pb.MessageRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  sendMessage(
    request: proto_random_pb.MessageRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/randomPackage.Random/SendMessage',
        request,
        metadata || {},
        this.methodDescriptorSendMessage,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/randomPackage.Random/SendMessage',
    request,
    metadata || {},
    this.methodDescriptorSendMessage);
  }

  methodDescriptorUserStream = new grpcWeb.MethodDescriptor(
    '/randomPackage.Random/UserStream',
    grpcWeb.MethodType.SERVER_STREAMING,
    proto_random_pb.StreamRequest,
    proto_random_pb.UserStreamResponse,
    (request: proto_random_pb.StreamRequest) => {
      return request.serializeBinary();
    },
    proto_random_pb.UserStreamResponse.deserializeBinary
  );

  userStream(
    request: proto_random_pb.StreamRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<proto_random_pb.UserStreamResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/randomPackage.Random/UserStream',
      request,
      metadata || {},
      this.methodDescriptorUserStream);
  }

  methodDescriptorChatStream = new grpcWeb.MethodDescriptor(
    '/randomPackage.Random/ChatStream',
    grpcWeb.MethodType.SERVER_STREAMING,
    proto_random_pb.StreamRequest,
    proto_random_pb.StreamMessage,
    (request: proto_random_pb.StreamRequest) => {
      return request.serializeBinary();
    },
    proto_random_pb.StreamMessage.deserializeBinary
  );

  chatStream(
    request: proto_random_pb.StreamRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<proto_random_pb.StreamMessage> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/randomPackage.Random/ChatStream',
      request,
      metadata || {},
      this.methodDescriptorChatStream);
  }

}

